[train]
batch_size = 36
epoch = 1000
learning_rate = 0.001
shuffle = 'True'
num_workers = 0
weight_decay=0.0001
early_stopping=100

[block]
    [block.init]
    dims = [[20, 256], [256, 128], [128, 64], [64, 32], [32, 20]]
    dropout = 0.25

    [block.inter]
    dims = [[40, 512], [512, 256], [256, 128], [128, 64], [64, 32], [32, 20]]
    dropout = 0.25

    [block.extract]
    dims = [[40, 20]]
    dropout = 0.25

    [block.read_pre_model]
    dims = [[20, 1]]
    activation = 'Sigmoid'
    dropout = 0.0

    [block.site_pre_model]
    dims = [[20, 1]]
    activation = 'IDENTITY'
#    activation = 'Sigmoid'
    dropout = 0.0


