[train]
batch_size = 256
epoch = 100
learning_rate = 1e-3

[metric]
loss_function = "binary_cross_entropy_loss"

[[layer]]
block_type = "DeaggregateNanopolish"
num_neighboring_features = 1

[[layer]]
block_type = "KmerMultipleEmbedding"
input_channel = 66
output_channel = 2
num_neighboring_features = 1

[[layer]]
block_type = "ConcatenateFeatures"

[[layer]]
block_type = "Linear"
input_channel = 15
output_channel = 150
activation = "relu"
batch_norm = true

[[layer]]
block_type = "Linear"
input_channel = 150
output_channel = 32
activation = "relu"
batch_norm = false

[[layer]]
block_type = "SigmoidProdPooling"
input_channel = 32
n_reads_per_site = 20